[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/firebase-config"
  to = "/.netlify/functions/firebase-config"
  status = 200

[[redirects]]
  from = "/supabase-config"
  to = "/.netlify/functions/supabase-config"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
